### ISSUE TITLE
Rückmeldung als Pflichtfeld markieren

### ISSUE THREAD

**Issue by wp99cp** [cevi/qualifikation#19]
Wenn ich eine neue Rückmeldung mit einem angehängten File erstelle, so erhalte ich eine `502 Bad Gateway
` Fehlermeldung, wenn ich das `Rückmeldung` Feld leer lasse.  Dies sollte im UI als Pflichfeld markiert werden.

URL: `/post`

**Comment by jeromesigg** [comment]
added 'required' to `Rückmeldung`
