### ISSUE TITLE
Keine Statusaktualisierung nach Abschluss 1. Selbsteinschätzung

### ISSUE THREAD

**Issue by ThomasHaefliger** [cevi/qualifikation#21]
Nach Klick auf "1. Selbsteinschätzung speichern und abschliessen" verbleibt diese in der TN-Ansicht als Status "Neu". In der Kursleiter-Ansicht
unter "Qualifikationen" springt der Balken nicht weiter sondern verbleibt bei "1. Selbsteinschätzung offen".

Es sind auch weiterhin Eingaben möglich, auch wenn diese nicht mehr gespeichert werden.

**Comment by ThomasHaefliger** [comment]
Kritisch für Start Qualiprozess am 1. April!

**Comment by ThomasHaefliger** [comment]
Oder ist das eine Einschränkung vom Demo-Kurs?

**Comment by jeromesigg** [comment]
Ist wahrscheinlich eine Einschränkung vom Demo-Kurs, da dieser keine Commits (Insert oder Updates) macht. An der Statusänderung wurde sonst noch nichts geändert

**Comment by ThomasHaefliger** [comment]
Vorschlag: Commits auf dem Kurs zulassen, damit Interessierte das Tool auch wirklich testen können (und auch wir, z.B. nach Update um die Funktion zu testen). Daten nächtlich auf Standard-Datenset zurücksetzen (Cronjob?)

**Comment by jeromesigg** [comment]
Commits für Qualis und Rückmeldungen werden zugelassen, Allgemein bei Kurs, Benutzer und Dateien nicht. Werden täglich durch Zufalls-Sätze überschrieben.

**Comment by jeromesigg** [comment]
Erledigt
