### ISSUE TITLE
Status "Teilnehmer Selbsteinschätzung abgeschlossen" wird nach Ausfüllen 1. Selbsteinschätzung gesetzt

### ISSUE THREAD

**Issue by ThomasHaefliger** [cevi/qualifikation#24]
TN füllt 1. Selbsteinschätzung aus und schliesst diese ab.
Danach wird der Status "Teilnehmer Selbsteinschätzung abgeschlossen" angezeigt.
Der Status "2. Selbsteinschätzung offen" fehlt.

**Comment by jeromesigg** [comment]
Der Status "2. Selbsteinschätzung offen" wird gesetzt, sobald der Button "Zweite Selbsteinschätzung freigeben" gedrückt wird. Qualis mit Status "Teilnehmer Selbsteinschätzung abgeschlossen werden dann auf Status "2. Selbsteinschätzung offen" gesetzt.
