### ISSUE TITLE
Alle Druckansichten der Qualifikationen als Bulk-Export

### ISSUE THREAD

**Issue by ThomasHaefliger** [cevi/qualifikation#25]
Funktion für die Kursleitung schaffen, alle Qualifikations-"Blätter" (Einschätzung und Spinne) aller TN in ein PDF zu exportieren (1 A4-Seite pro TN).
Zweck: Backup bei laufendem Kurs

**Comment by jeromesigg** [comment]
Mit "Möglichkeit alle Qualifikationen zu drucken" auf der Seite Qualifikationen gelöst, zeigt Druckversion an.

**Comment by ThomasHaefliger** [comment]
Danke! :)
