### ISSUE TITLE
Bei Rückmeldungen hochgeladene Dateien können nicht wieder heruntergeladen werden

### ISSUE THREAD

**Issue by ThomasHaefliger** [cevi/qualifikation#26]
Es wird bei Klick auf hochgeladene Datei nochmals die Person in neuem Tab geöffnet.

**Comment by ThomasHaefliger** [comment]
scheint nur im Firefox nicht zu funktionieren. Chromium geht.

**Comment by jeromesigg** [comment]
Wurde korrigiert, war für Leiter möglich aber nicht Kursleiter.
