### ISSUE TITLE
Leiter-Qualifikation: zusätzliches Bemerkungsfeld

### ISSUE THREAD

**Issue by ThomasHaefliger** [cevi/qualifikation#28]
Wunsch:
für den GL beim Ausfüllen der Qualifikation ein separates Textfeld für freien Text (was man dem TN noch mitgeben möchte, Tipps für die Zukunft, "Auflagen", ...).
Für TN nicht sichtbar, nur für Leiterteam. Auf Ausdruck sichtbar.

**Comment by jeromesigg** [comment]
Bemerkungsfeld erstellt
