### ISSUE TITLE
Stab-Mitarbeiter Berechtigungen einstellbar

### ISSUE THREAD

**Issue by ThomasHaefliger** [cevi/qualifikation#29]
Wunsch:
Bei Stab-Mitarbeitern (im GLK3 häufig ebenfalls J+S-Experten) möchte ich einstellen können, dass sie entweder gleiche Rechte wie GL's haben (aber alle TN in der Übersicht sichtbar) oder dass sie ebenfalls Kursleiter-Rechte haben.
Müsste man noch die Stab-Rolle via DB abfragen oder?

**Comment by jeromesigg** [comment]
Neue Rolle "Stabsleitende", gleiches Recht wie GL inkl. alle Qualis sehen.
