### ISSUE TITLE
Path to Camp Files may not be unique

### ISSUE THREAD

**Issue by wp99cp** [cevi/qualifikation#31]
If there exist multiple camps with the same name, the use the same folder, e.g.:

/var/www/html/storage/app/files/glk1

**Comment by jeromesigg** [comment]
Camp ID is added to path

**Comment by wp99cp** [comment]
> Camp ID is added to path

Does this fix this issue?

**Comment by jeromesigg** [comment]
Yes, with camp_id the folder is unique, app/files/101_glk1 or app/files/103_glk1
