### ISSUE TITLE
TN ohne Ceviname

### ISSUE THREAD

**Issue by ThomasHaefliger** [cevi/qualifikation#38]
Es soll Leute ohne Cevinamen geben :)
Wenn kein Ceviname vorhanden -> zeige Vorname Nachname
<img width="174" alt="2024-03-13 22_48_34-Personen - Qualifikationen – Mozilla Firefox" src="https://github.com/cevi/qualifikation/assets/26150741/34735f0d-ed75-4b4b-a639-023bee3fed46">

**Comment by ThomasHaefliger** [comment]
gerade festgestellt, dass bei anderen TN ohne Ceviname korrekt einfach der Vorname angezeigt wird.

**Comment by jeromesigg** [comment]
Meiner Meinung nach ein klarer Fall von Shit In = Shit out. Robin Fuchs hat - als Cevinamen auf der DB. Siehe Desirée im gleichen Kurs, da wird korrekt der Vorname angezeigt

**Comment by ThomasHaefliger** [comment]
Tatsache, in der DB war ein - beim Ceviname...
