### ISSUE TITLE
Teilnehmer als Favoriten markieren

### ISSUE THREAD

**Issue by marcoagostini** [cevi/qualifikation#47]
Ich als Gruppenleiter würde gerne die Teilnehmer meiner Gruppe als Favoriten hinterlegen, sodass nur diese nur angezeigt werden oder sie gesondert angezeigt werden. Zusätzlich zur bereits bestehenden Funktion. :-)

**Comment by jeromesigg** [comment]
mit #52  gelöst. Eigene Teilnehmer erscheinen zuoberst
