### ISSUE TITLE
Seite "Alle Personen" / "Person erstellen" aufräumen

### ISSUE THREAD

**Issue by ThomasHaefliger** [cevi/qualifikation#7]
zB auf https://quali.cevi.tools/admin/users befindet sich der Link zum Download der Vorlage ganz oben, das Upload-Feld dann aber ganz unten. Das und der Button für den Import aus der CeviDB erstellt ja auch Personen, unter "Person erstellen" kann aber nur eine Person erstellt werden.
Vorschlag: mit dem Issue #4 das Menü jeweils dynamisch an die dem Prozess logisch zugehörigen Aktionen anpassen.

**Comment by jeromesigg** [comment]
Seite aufgeräumt, neues Admin Dashboard
