### ISSUE TITLE
Footer mitten in der Seite

### ISSUE THREAD

**Issue by ThomasHaefliger** [cevi/qualifikation#8]
Footer bleibt nicht unten, sobald gescrollt werden muss
![footer](https://user-images.githubusercontent.com/26150741/147650643-ccb28e1b-cd78-4e55-a388-f09ef0d3b546.jpg)
.

**Comment by ThomasHaefliger** [comment]
auch bei anderen Seiten festgestellt

**Comment by jeromesigg** [comment]
Seiten überprüft, sollten korrigiert sein
